### ISSUE TITLE
Change pause/play

### ISSUE THREAD

**Issue by franziskuskiefer** [mafflin/media-keys#1]
It would be great if the pause icon could change to a play icon when paused.

**Comment by mafflin** [comment]
When what paused? moc? Rhythmbox? Or, maybe, youtube and Google play music? ))

**Comment by corebots** [comment]
when you pause the player you've pressed play for, obviously... ?

**Comment by mafflin** [comment]
Integration of MPRIS2 would make this tiny extension as heavy as fuck!

**Comment by corebots** [comment]
i see :/
