### ISSUE TITLE
Wrong icon

### ISSUE THREAD

**Issue by redianthus** [mafflin/media-keys#2]
Hi,

Just installed media-keys from `master` and then from `mote`, in both case, here's how it looks:

![capture du 2016-09-18 14-30-25-small](https://cloud.githubusercontent.com/assets/16472988/18615696/38a83446-7dad-11e6-8dad-0c0a94ea589a.png)

According to the screenshot on the gnome shell extensions website, it's not the expected behaviour.

I'm running Gnome 3.21.92. If you need more informations, just ask. Thanks!

**Comment by mafflin** [comment]
Fixed. Thanx!
