### ISSUE TITLE
Media keys don't do anything on Ubuntu GNOME

### ISSUE THREAD

**Issue by Snowman3456** [mafflin/media-keys#4]
I just see this when used:

![](https://i.imgur.com/zZDZVrh.png)

**Comment by mafflin** [comment]
Yep! They just emulates Media Keys. And you can bind any action to you media keys in gnome settings.

**Comment by Snowman3456** [comment]
@mafflin That doesn't work - they are already bound to the correct media action - the issue is that PMP isn't recognizing that action internally. Volume +/- works because it's system-wide. Pause/Play or Skip next for instance result in the above icon because no subsystem is receiving the action.

All media keys are recognized in SMPlayer/VLC natively on Ubuntu GNOME so this still needs to be re-opened.

Plex needs to work with them still.

**Comment by Snowman3456** [comment]
@mafflin This still needs to be re-opened. Plex needs to register itself in some manner to handle these media key actions.

**Comment by Snowman3456** [comment]
@mafflin Plex needs to listen for these keybinds:

![media_keys](https://user-images.githubusercontent.com/4528283/30675711-fcf29d46-9e4f-11e7-9ea6-fa7c62869356.png)

**Comment by mafflin** [comment]
@Enigma0 just disable the keys.
![screenshot from 2017-09-27 22-25-19](https://user-images.githubusercontent.com/14847258/30933334-f088591e-a3d2-11e7-9ad4-ce1a4daede3e.png)
